version: '3'
services:
  web:
    build: .
    ports:
      - "6002:5000"

    environment:
      - PYTHONUNBUFFERED=1
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always