version: '3'
services:
  app:
    hostname: 2pptx
    image: 2pptx:main
    build: .
    ports:
      - "$PORT:5000"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always
    networks:
      nginx_proxy_net:
networks:
  nginx_proxy_net:
    external: true
