version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 2pptx:latest
    ports:
      - "$PORT:5000" # Externer Port 6002 wird auf internen Port 5000 gemappt
    environment:
      FLASK_ENV: production
      FLASK_APP: app.py
    volumes:
      - .:/app # Bindet das aktuelle Verzeichnis ins Containerverzeichnis /app
    working_dir: /app
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always